// Auto-generated by tools/download_fensterversand_images.py
// Re-run the script after updating DOWNLOAD_MAP to refresh assets.

export const CONFIGURATOR_IMAGE_BASE = '/assets/configurator';
export const CATALOG_IMAGE_BASE = '/assets/catalog';

export function configuratorImage(filename) {
  return `${CONFIGURATOR_IMAGE_BASE}/${filename}`;
}

export function catalogImage(filename) {
  return `${CATALOG_IMAGE_BASE}/${filename}`;
}

export const PRODUCT_IMAGES = {
  window: catalogImage('product-fenster.png'),
  door: catalogImage('product-door.png'),
  shutter: catalogImage('product-shutter.png'),
};

/** Neutral front-view window shown in live preview at configuration start. */
export const WINDOW_DEFAULT_PREVIEW = catalogImage('window-default-preview.png');

/** Catalog photos keyed by decor colour id for the live preview. */
export const DECOR_PREVIEW_IMAGES = {
  Weiss: catalogImage('weib.png')
};

export const MATERIAL_IMAGES = {
  Kunststoff: catalogImage('material-kunststoff.png'),
  'Kunststoff-Aluminium': catalogImage('material-kunststoff-alu.png'),
  Holz: catalogImage('material-holz.png'),
  'Holz-Aluminium': catalogImage('material-holz-alu.png'),
  Aluminium: catalogImage('material-aluminium.png'),
};

/** Only types with dedicated artwork; others use generated SVG shapes in defaults.js */
export const WINDOW_TYPE_IMAGES = {
  'Balkontuer einteilig': catalogImage('window-balkontuer-einteilig.png'),
  'Balkontuer zweiteilig': catalogImage('window-balkontuer-zweiteilig.png'),
  'Parallel-Schiebe-Kipp': catalogImage('window-psk.png'),
  'Hebe-Schiebetuer': catalogImage('window-hebeschiebe.png'),
  Sondertyp: catalogImage('window-sondertyp.png')
};

export const OPTION_ICON_IMAGES = {
  glass: configuratorImage('glass.svg'),
  sound: configuratorImage('sound.svg'),
  security: configuratorImage('security.svg'),
  handle: configuratorImage('handle.svg'),
  frame: configuratorImage('frame.svg'),
};

/** @deprecated Use PRODUCT_IMAGES */
export const PRODUCT_IMAGE_MANIFEST = PRODUCT_IMAGES;
/** @deprecated Use MATERIAL_IMAGES */
export const MATERIAL_IMAGE_MANIFEST = MATERIAL_IMAGES;
/** @deprecated Use WINDOW_TYPE_IMAGES */
export const WINDOW_TYPE_IMAGE_MANIFEST = WINDOW_TYPE_IMAGES;
