// Auto-generated by tools/download_fensterversand_images.py
// Re-run the script after updating DOWNLOAD_MAP to refresh assets.

export const CONFIGURATOR_IMAGE_BASE = '/assets/configurator';

export function configuratorImage(filename) {
  return `${CONFIGURATOR_IMAGE_BASE}/${filename}`;
}

export const PRODUCT_IMAGES = {
  window: configuratorImage('product-fenster.png'),
  door: configuratorImage('product-door.png'),
  shutter: configuratorImage('product-shutter.png'),
};

export const MATERIAL_IMAGES = {
  Kunststoff: configuratorImage('material-kunststoff.png'),
  "Kunststoff-Aluminium": configuratorImage('material-kunststoff-alu.png'),
  Holz: configuratorImage('material-holz.png'),
  "Holz-Aluminium": configuratorImage('material-holz-alu.png'),
  Aluminium: configuratorImage('material-aluminium.png'),
};

/** Only types with dedicated artwork; others use generated SVG shapes in defaults.js */
export const WINDOW_TYPE_IMAGES = {
  'Balkontuer einteilig': configuratorImage('window-balkontuer-einteilig.png'),
  'Balkontuer zweiteilig': configuratorImage('window-balkontuer-zweiteilig.png'),
  'Parallel-Schiebe-Kipp': configuratorImage('window-psk.png'),
  'Hebe-Schiebetuer': configuratorImage('window-hebeschiebe.png'),
  Sondertyp: configuratorImage('window-sondertyp.png')
};

export const OPTION_ICON_IMAGES = {
  glass: configuratorImage('glass.svg'),
  sound: configuratorImage('sound.svg'),
  security: configuratorImage('security.svg'),
  handle: configuratorImage('handle.svg'),
  frame: configuratorImage('frame.svg'),
};

/** @deprecated Use PRODUCT_IMAGES */
export const PRODUCT_IMAGE_MANIFEST = PRODUCT_IMAGES;
/** @deprecated Use MATERIAL_IMAGES */
export const MATERIAL_IMAGE_MANIFEST = MATERIAL_IMAGES;
/** @deprecated Use WINDOW_TYPE_IMAGES */
export const WINDOW_TYPE_IMAGE_MANIFEST = WINDOW_TYPE_IMAGES;
