export {
  CONFIGURATOR_IMAGE_BASE,
  configuratorImage,
  MATERIAL_IMAGE_MANIFEST,
  MATERIAL_IMAGES,
  OPTION_ICON_IMAGES,
  PRODUCT_IMAGE_MANIFEST,
  PRODUCT_IMAGES,
  WINDOW_TYPE_IMAGE_MANIFEST,
  WINDOW_TYPE_IMAGES
} from './configuratorImages';

export {
  ALUDEC_DECORS,
  DECOR_SONDER_COLORS,
  DECOR_STANDARD_COLORS,
  WOODEC_DECORS
} from './decorColors';

export * from './windowTypeImageManifest';
